version: "3"
services:
  kindle:
    build: .
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./wineuser:/home/wineuser
    command: find /tmp/kindle_installer/ -print0 | xargs -0 wine 
    #command: wine '/home/wineuser/.wine/drive_c/Program Files (x86)/Amazon/Kindle/Kindle.exe'
